name: todo_bloc
description: A new Flutter project.
publish_to: 'none' 
version: 1.0.0+1

environment:
  sdk: '>=2.19.4 <3.0.0'

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  
  flutter_bloc: ^8.1.2
  equatable: ^2.0.5
  font_awesome_flutter: ^10.4.0
  bloc: ^8.1.1
  hydrated_bloc: ^9.1.0
  path_provider: ^2.0.13
  uuid: ^3.0.7

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0


flutter:
  uses-material-design: true

        
    
    
                                      